pkgs: with pkgs; [
        neovim
        kitty
        obsidian
        # vlc not available for apple silicon, need to use homebrew for that one
        vscode
        raycast
        bat
        btop
        eza
        fastfetch
        fd
        fzf
        git
        gnupg
        htop
        lazygit
        mediainfo
        nixfmt-rfc-style
        nodejs_24
        podman
        python313
        ripgrep
        speedtest-cli
        starship
        stow
        tailscale
        tmux
        ueberzugpp
        uv
        yazi
        yt-dlp
        zoxide
]