import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
italic = { family = "Hack Nerd Font", style = "Italic" }
size = 15

[window]
decorations = "Buttonless"
dimensions = { columns = 200, lines = 55 }
dynamic_title = true
padding = { x = 1, y = 3 }

[cursor]
style = { shape="Block", blinking="Always"}

