import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "screen-256color"

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
italic = { family = "Hack Nerd Font", style = "Italic" }
size = 18

[window]
decorations = "Buttonless"
dimensions = { columns = 200, lines = 55 }
dynamic_title = false
title = "Alacritty"

[cursor]
style = { shape="Block", blinking="Always"}

